# This file used for both developer and demo purposes.
# It contains environment
version: '3.7'

services:
  traefik:
    image: traefik:v2.4.8
    hostname: traefik
    restart: unless-stopped
    # The Static Configuration
    command: --configFile=/traefik_conf/traefik.yml
    ports:
      - 8083:8081
    extra_hosts:
      # https://github.com/moby/moby/pull/40007
      # works on Docker for Mac 3.4.0 or Linux Docker 20.10.4
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik_conf:/traefik_conf

  # static server
  frontend:
    image: nginx:1.16.0
    restart: unless-stopped
    ports:
      - 8084:8082
    volumes:
      - ./frontend-nginx:/usr/share/nginx/html:ro
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  mortgage-application-postgresql:
    image: postgres:13.4
    restart: unless-stopped
    ports:
      - 5444:5432
    volumes:
      - ./docker/postgresql_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mortgage_application_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  kratos-postgresql:
    image: postgres:13.4
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - kratos_postgres_data:/var/lib/postgresql/data

  kratos-migrate:
    image: oryd/kratos:v0.7.4-alpha.1
    environment:
      - DSN=postgres://kratos:secret@kratos-postgresql:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - SQA_OPT_OUT=true
    restart: on-failure
    depends_on:
      - kratos-postgresql
    command: migrate sql -e -y

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.7.4-alpha.1
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=cookie
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    restart: on-failure
    ports:
      - "4455:4455"

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.7.4-alpha.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@kratos-postgresql:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SQA_OPT_OUT=true
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./docker/kratos-email-password
        # https://www.ory.sh/kratos/docs/reference/configuration
        target: /etc/config/kratos

volumes:
  mortgage_application_postgres_data:
  kratos_postgres_data: