camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Admin
  filter:
    create: All tasks
  authorization:
    enabled: true

spring.datasource:
  # https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters
  url: jdbc:postgresql://localhost:5444/camunda?connectTimeout=10&socketTimeout=40
  username: camunda
  password: "camundapassword"
  driverClassName: org.postgresql.Driver

server:
  port: 8066
